import { requireAdminPage } from "@/lib/admin-page";
import { listAdminAudit } from "@/lib/admin-management";
import { finishLabels,type AvailableFinish } from "@/lib/card-metadata";
import { permissionLabels } from "@/lib/admin-permissions";
import { AdminShell } from "@/components/admin-shell";
const actions:Record<string,string>={"economy.prices":"Tarifs de carte modifiés","catalogue.scan":"Recherche du catalogue demandée","catalogue.import.set":"Set importé","catalogue.import.request":"Import validé","catalogue.import.card":"Carte importée","catalogue.import.finish":"Import terminé","role.create":"Rôle créé","role.update":"Rôle modifié","role.archive":"Rôle archivé","role.restore":"Rôle restauré","account.roles":"Rôles d’un compte modifiés","configuration.update":"Configuration modifiée","catalogue.set":"Disponibilité d’un set modifiée","catalogue.card":"Disponibilité d’une carte modifiée","catalogue.metadata":"Fiche de carte modifiée","catalogue.image":"Image de carte ajoutée"};
function Snapshot({value,label}:{value:unknown;label:string}){
 const snapshot=value as {priceRules?:{scope:string;values:{finish:AvailableFinish;coins:number|null;gems:number|null}[]};name?:string;description?:string;permissions?:string[];roles?:string[];archived?:boolean;affectedAccounts?:string[];importSummary?:string;jobId?:string;reason?:string;cardMetadata?:{name:string;localId:string;rarity:string;illustrator:string;finishes:string[]};imageAvailable?:boolean;availability?:{kind:string;active?:boolean;excluded?:boolean};configuration?:{maintenanceEnabled:boolean;maintenanceMessage:string;registrationsEnabled:boolean;registrationMessage:string}}|null;
 return <section><h3>{label}</h3>{!snapshot?<p>Aucun état précédent.</p>:<>{snapshot.priceRules&&<div><p>{snapshot.priceRules.scope==="card"?"Exception par carte":"Tarifs par rareté"}</p><dl>{snapshot.priceRules.values.map(value=><div key={value.finish}><dt>{finishLabels[value.finish]}</dt><dd>Pièces : {value.coins===null?(snapshot.priceRules?.scope==="card"?"Tarif général":"À définir"):value.coins.toLocaleString("fr-FR")} · Gemmes : {value.gems===null?(snapshot.priceRules?.scope==="card"?"Tarif général":"À définir"):value.gems.toLocaleString("fr-FR")}</dd></div>)}</dl></div>}{snapshot.name&&<p><strong>{snapshot.name}</strong>{snapshot.archived?" · Archivé":""}</p>}{snapshot.description&&<p>{snapshot.description}</p>}{snapshot.roles&&<p>Rôles : {snapshot.roles.join(", ")||"aucun"}</p>}{snapshot.affectedAccounts&&<p>Comptes concernés : {snapshot.affectedAccounts.join(", ")||"aucun"}</p>}{snapshot.configuration&&<dl className="admin-config-audit"><dt>Maintenance</dt><dd>{snapshot.configuration.maintenanceEnabled?"Activée":"Désactivée"}</dd><dt>Message de maintenance</dt><dd className="availability-message">{snapshot.configuration.maintenanceMessage}</dd><dt>Inscriptions</dt><dd>{snapshot.configuration.registrationsEnabled?"Ouvertes":"Fermées"}</dd><dt>Message de fermeture</dt><dd className="availability-message">{snapshot.configuration.registrationMessage}</dd></dl>}{snapshot.importSummary&&<p>{snapshot.importSummary}</p>}{snapshot.reason&&<p>{snapshot.reason}</p>}{typeof snapshot.imageAvailable==="boolean"&&<p>{snapshot.imageAvailable?"Image disponible":"Image absente"}</p>}{snapshot.cardMetadata&&<dl><dt>Nom</dt><dd>{snapshot.cardMetadata.name||"Manquant"}</dd><dt>Numéro</dt><dd>{snapshot.cardMetadata.localId||"Manquant"}</dd><dt>Rareté</dt><dd>{snapshot.cardMetadata.rarity||"Manquante"}</dd><dt>Illustrateur</dt><dd>{snapshot.cardMetadata.illustrator||"Manquant"}</dd><dt>Finitions</dt><dd>{snapshot.cardMetadata.finishes.map(key=>(finishLabels[key as AvailableFinish]??key)).join(", ")||"Manquantes"}</dd></dl>}{snapshot.availability&&<p>{snapshot.availability.kind==="set"?(snapshot.availability.active?"Set actif":"Set inactif"):(snapshot.availability.excluded?"Carte exclue de l’obtention":"Carte autorisée si le set est actif")}</p>}{snapshot.permissions&&<ul>{snapshot.permissions.map(key=><li key={key}>{permissionLabels[key]??key}</li>)}</ul>}</>}</section>;
}
export default async function AuditPage({searchParams}:{searchParams:Promise<{page?:string}>}){
 const session=await requireAdminPage("audit.read"),params=await searchParams,page=Math.min(10000,Math.max(0,Math.floor(Number(params.page)||0)));
 const rows=await listAdminAudit(page);
 return <AdminShell access={session.access} active="/admin/journal" title="Le journal de l’équipe" description="Les changements de rôles, d’attributions de configuration et du catalogue conservent leur auteur et leur date.">
 <section className="admin-target-panel"><p>Historique en lecture seule. Les changements appliqués à un rôle concernent tous les comptes auxquels il est attribué.</p></section>
 <div className="admin-audit-list">{rows.slice(0,30).map(row=><article className="admin-audit-card" key={row.id}><header><div><span className="admin-context-tag">{actions[row.action]??row.action}</span><h2>{row.targetName}</h2><p>Par {row.actorName}</p></div><time dateTime={row.createdAt.toISOString()}>{row.createdAt.toLocaleString("fr-FR",{timeZone:"Europe/Paris",dateStyle:"medium",timeStyle:"short"})}</time></header><details><summary>Voir les changements</summary><div className="admin-audit-diff"><Snapshot label="Avant" value={row.before}/><Snapshot label="Après" value={row.after}/></div></details></article>)}</div>
 {!rows.length&&<section className="admin-target-panel"><h2>Le journal attend sa première action</h2><p>Les changements de rôles, d’attributions de configuration et du catalogue apparaîtront ici.</p></section>}
 <nav className="admin-pagination" aria-label="Pages du journal">{page>0&&<a className="quiet-button" href={"/admin/journal?page="+(page-1)}>Page précédente</a>}<span>Page {page+1}</span>{rows.length>30&&<a className="quiet-button" href={"/admin/journal?page="+(page+1)}>Page suivante</a>}</nav></AdminShell>;
}
