CREATE TABLE "game_sets" (
  "code" varchar(12) PRIMARY KEY,
  "name" text NOT NULL,
  "series_name" text NOT NULL DEFAULT '',
  "release_date" date,
  "official_card_count" integer NOT NULL DEFAULT 0,
  "total_card_count" integer NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT false,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "game_sets_active_idx" ON "game_sets" USING btree ("active");
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('AOR', 'Origines Antiques', 'XY', '2015-08-12', 98, 101) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('AQ', 'Aquapolis', 'e-cards', '2003-01-15', 147, 186) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('ASC', 'Héros Transcendants', 'Méga-Évolution', '2026-01-30', 217, 295) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('ASR', 'Astres Radieux', 'Épée et Bouclier', '2022-05-27', 189, 216) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('B2', 'Base Set 2', 'Base', '2000-02-24', 130, 130) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BKP', 'Rupture Turbo', 'XY', '2016-02-03', 122, 126) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BKT', 'Impulsion Turbo', 'XY', '2015-11-04', 162, 165) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BLK', 'Foudre Noire', 'Écarlate et Violet', '2025-07-17', 86, 172) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BLW', 'Noir & Blanc', 'Noir & Blanc', '2011-04-25', 114, 115) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BRS', 'Stars Étincelantes', 'Épée et Bouclier', '2022-02-25', 172, 186) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BS', 'Set de Base', 'Base', '1999-01-09', 102, 102) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BST', 'Styles de combat', 'Épée et Bouclier', '2021-03-19', 163, 183) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('BUS', 'Ombres Ardentes', 'Soleil et Lune', '2017-08-04', 147, 169) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CC', 'Poké Card Creator Pack', 'EX', '2004-07-01', 5, 5) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CEC', 'Éclipse Cosmique', 'Soleil et Lune', '2019-11-01', 236, 271) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CEL', 'Célébrations', 'Épée et Bouclier', '2021-10-08', 25, 25) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CES', 'Tempête Céleste', 'Soleil et Lune', '2018-08-03', 168, 183) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CG', 'EX Gardiens de Cristal', 'EX', '2006-08-30', 100, 100) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CIN', 'Invasion Carmin', 'Soleil et Lune', '2017-11-03', 111, 125) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CL', 'L''appel des Légendes', 'L''appel des Légendes', '2011-02-09', 95, 106) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CPA', 'La Voie du Maître', 'Épée et Bouclier', '2020-09-25', 73, 80) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CRE', 'Règne de Glace', 'Épée et Bouclier', '2021-06-18', 198, 233) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CRI', 'Chaos Ascendant', 'Méga-Évolution', '2026-05-22', 86, 122) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('CRZ', 'Zénith Suprême', 'Épée et Bouclier', '2023-01-20', 159, 160) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DAA', 'Ténèbres Embrasées', 'Épée et Bouclier', '2020-08-14', 189, 201) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DCR', 'Double Danger', 'XY', '2015-03-25', 34, 34) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DF', 'EX Île des Dragons', 'EX', '2006-11-08', 101, 101) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DP', 'Diamant & Perle', 'Diamant & Perle', '2007-05-01', 130, 130) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DR', 'EX Dragon', 'EX', '2003-11-24', 97, 100) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DRI', 'Rivalités Destinées', 'Écarlate et Violet', '2025-05-30', 182, 244) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DRM', 'Majesté Des Dragons', 'Soleil et Lune', '2018-09-07', 70, 78) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DRV', 'Coffre des Dragons', 'Noir & Blanc', '2012-10-05', 20, 21) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DS', 'EX Espèces Delta', 'EX', '2005-10-31', 113, 114) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('DX', 'EX Deoxys', 'EX', '2005-02-01', 107, 108) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('EM', 'EX Émeraude', 'EX', '2005-05-09', 106, 107) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('EVO', 'Évolutions', 'XY', '2016-11-02', 108, 113) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('EVS', 'Évolution Céleste', 'Épée et Bouclier', '2021-08-27', 203, 237) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('EX', 'Expedition', 'e-cards', '2002-09-15', 165, 165) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FCO', 'Impact des Destins', 'XY', '2016-05-02', 124, 129) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FFI', 'Poings Furieux', 'XY', '2014-08-13', 111, 114) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FLF', 'Étincelles', 'XY', '2014-05-07', 106, 110) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FLI', 'Lumière Interdite', 'Soleil et Lune', '2018-05-04', 131, 146) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FO', 'Fossile', 'Base', '1999-10-10', 62, 62) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('FST', 'Poing de Fusion', 'Épée et Bouclier', '2021-11-12', 264, 284) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('GEN', 'Générations', 'XY', '2016-02-22', 83, 117) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('GRI', 'Gardiens Ascendants', 'Soleil et Lune', '2017-05-05', 145, 169) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('HIF', 'Destinées Occultes', 'Soleil et Lune', '2019-08-23', 68, 69) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('HL', 'EX Légendes Oubliées', 'EX', '2004-06-01', 101, 102) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('HP', 'EX Fantômes Holon', 'EX', '2006-05-03', 110, 111) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('HS', 'HeartGold SoulSilver', 'HeartGold SoulSilver', '2010-02-10', 123, 124) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('JTG', 'Aventures Ensemble', 'Écarlate et Violet', '2025-03-28', 159, 190) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('JU', 'Jungle', 'Base', '1999-06-16', 64, 64) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('LG', 'Legendary Collection', 'Legendary Collection', '2002-05-24', 110, 110) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('LM', 'EX Créateurs de légendes', 'EX', '2006-02-13', 92, 93) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('LOR', 'Origine Perdue Galerie de Dresseurs', 'Épée et Bouclier', '2022-09-09', 30, 30) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('LOT', 'Tonnerre Perdu', 'Soleil et Lune', '2018-11-02', 214, 236) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('MA', 'EX Team Magma vs Team Aqua', 'EX', '2004-03-01', 95, 97) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('MEG', 'Méga-Évolution', 'Méga-Évolution', '2025-09-26', 132, 188) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('MEW', 'Écarlate et Violet', 'Écarlate et Violet', '2023-03-31', 198, 258) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('N1', 'Neo Genesis', 'Neo', '2000-12-16', 111, 111) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('N2', 'Neo Discovery', 'Neo', '2001-06-01', 75, 75) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('N3', 'Neo Revelation', 'Neo', '2001-09-21', 64, 66) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('N4', 'Neo Destiny', 'Neo', '2002-02-28', 105, 113) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('OBF', 'Flammes Obsidiennes', 'Écarlate et Violet', '2023-08-11', 197, 230) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P1', 'POP Série 1', 'POP', '2004-09-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P2', 'POP Série 2', 'POP', '2005-08-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P3', 'POP Série 3', 'POP', '2006-04-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P4', 'POP Série 4', 'POP', '2006-08-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P5', 'POP Series 5', 'POP', '2007-03-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P6', 'POP Series 6', 'POP', '2007-09-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P7', 'POP Série 7', 'POP', '2008-03-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P8', 'POP Series 8', 'POP', '2008-09-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('P9', 'POP Série 9', 'POP', '2009-03-01', 17, 17) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PAF', 'Destinées de Paldea', 'Écarlate et Violet', '2024-01-26', 91, 245) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PAL', 'Évolutions à Paldea', 'Écarlate et Violet', '2023-06-09', 193, 279) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PAR', 'Faille Paradoxe', 'Écarlate et Violet', '2023-11-03', 182, 266) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PBL', 'Nuit Noire', 'Méga-Évolution', '2026-07-17', 84, 120) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PFL', 'Flammes Fantasmagoriques', 'Méga-Évolution', '2025-11-14', 94, 130) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PHF', 'Vigueur Spectrale', 'XY', '2014-11-05', 119, 124) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PK', 'EX Gardiens du Pouvoir', 'EX', '2007-02-17', 108, 108) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PL', 'Platine', 'Platine', '2009-02-11', 127, 133) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('POR', 'Équilibre Parfait', 'Méga-Évolution', '2026-03-27', 88, 124) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PRC', 'Primo-Choc', 'XY', '2015-02-04', 160, 164) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('PRE', 'Évolutions Prismatiques', 'Écarlate et Violet', '2025-01-17', 131, 180) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('RCL', 'Clash des Rebelles', 'Épée et Bouclier', '2020-05-01', 192, 209) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('RG', 'EX Rouge Feu & Vert Feuille', 'EX', '2004-09-01', 112, 116) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('ROS', 'Ciel Rugissant', 'XY', '2015-05-06', 108, 112) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('RS', 'EX Rubis & Saphir', 'EX', '2003-07-01', 109, 109) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SCR', 'Couronne Stellaire', 'Écarlate et Violet', '2024-09-13', 142, 175) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SFA', 'Fable Nébuleuse', 'Écarlate et Violet', '2024-08-02', 64, 99) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SHF', 'Destinées Radieuses', 'Épée et Bouclier', '2021-02-19', 72, 73) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SIT', 'Tempête Argentée Galerie de Dresseurs', 'Épée et Bouclier', '2022-11-11', 30, 30) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SK', 'Skyridge', 'E-Card', '2003-05-12', 144, 182) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SLG', 'Légendes Brillantes', 'Soleil et Lune', '2017-10-06', 73, 78) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SS', 'EX Tempête de sable', 'EX', '2003-09-18', 100, 100) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SSH', 'Épée et Bouclier', 'Épée et Bouclier', '2020-02-07', 202, 216) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SSP', 'Étincelles Déferlantes', 'Écarlate et Violet', '2024-11-08', 191, 252) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('STS', 'Offensive Vapeur', 'XY', '2016-08-03', 114, 116) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SUM', 'Soleil et Lune', 'Soleil et Lune', '2017-02-03', 149, 163) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('SVI', 'Écarlate et Violet', 'Écarlate et Violet', '2023-03-31', 198, 258) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TEF', 'Forces Temporelles', 'Écarlate et Violet', '2024-03-22', 162, 218) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TEU', 'Duo de Choc', 'Soleil et Lune', '2019-01-31', 181, 196) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TM', 'Triomphant', 'HeartGold SoulSilver', '2010-11-03', 102, 103) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TR', 'Team Rocket', 'Base', '2000-04-24', 82, 83) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TRR', 'Team Rocket Returns', 'EX', '2004-11-01', 109, 111) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('TWM', 'Mascarade Crépusculaire', 'Écarlate et Violet', '2024-05-24', 167, 226) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('UD', 'Indomptable', 'HeartGold SoulSilver', '2010-08-18', 90, 91) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('UF', 'EX Forces Cachées', 'EX', '2005-08-22', 115, 117) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('UL', 'Déchaînement', 'HeartGold SoulSilver', '2010-05-12', 95, 96) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('UNB', 'Alliance Infaillible', 'Soleil et Lune', '2019-05-03', 214, 234) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('UNM', 'Harmonie des Esprits', 'Soleil et Lune', '2019-08-02', 236, 258) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('VIV', 'Voltage Éclatant', 'Épée et Bouclier', '2020-11-13', 185, 203) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('WHT', 'Flamme Blanche', 'Écarlate et Violet', '2025-07-17', 86, 173) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "game_sets" ("code","name","series_name","release_date","official_card_count","total_card_count") VALUES ('XY', 'XY', 'XY', '2014-02-05', 146, 146) ON CONFLICT ("code") DO NOTHING;
