"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { Search,RefreshCw,Download,CalendarClock } from "lucide-react";
import type { readImportDashboard } from "@/lib/catalogue-import-management";
import type { DiscoveryItem } from "@/lib/catalogue-import-types";
type Dashboard=Awaited<ReturnType<typeof readImportDashboard>>;
const statuses:Record<string,string>={queued:"En attente",running:"En cours",complete:"Terminé",partial:"Résultat partiel",failed:"Échec"};
function time(value:Date|string|null|undefined){return value?new Date(value instanceof Date?value.getTime():value).toLocaleString("fr-FR",{timeZone:"Europe/Paris",dateStyle:"medium",timeStyle:"short"}):"Non disponible";}
function Proposal({item,reportId,canImport,disabled,approve}:{item:DiscoveryItem;reportId:string;canImport:boolean;disabled:boolean;approve:(body:Record<string,unknown>)=>Promise<void>}){
 const [localCode,setLocalCode]=useState(item.localCode),[tcgdexId,setTcgdexId]=useState(item.tcgdexId),[confirmed,setConfirmed]=useState(false);
 return <article className="import-proposal"><header><div><span className="admin-context-tag">{item.sourceCode} · {item.complete?"Checklist lue":"Lecture incomplète"}</span><h3>{item.name}</h3><p>{item.missing} carte(s) absente(s) · {item.existing} déjà présente(s) · {item.cards.length} / {item.expected} lues</p></div><a className="quiet-button" href={"https://www.pokecardex.com/series/"+item.sourceCode} target="_blank" rel="noreferrer">Voir la source</a></header>
 <p>{item.mapping}</p>{item.issues.length>0&&<ul className="import-issues">{item.issues.map((issue,index)=><li key={index}>{issue}</li>)}</ul>}
 <details><summary>Vérifier les cartes et la correspondance</summary><div className="import-mapping"><label>Code interne du set<input value={localCode} maxLength={12} disabled={!canImport||disabled} onChange={event=>{setLocalCode(event.target.value.toUpperCase());setConfirmed(false);}}/></label><label>Identifiant TCGdex (facultatif)<input value={tcgdexId} maxLength={40} disabled={!canImport||disabled} onChange={event=>{setTcgdexId(event.target.value);setConfirmed(false);}}/></label></div>
 <p>Le code interne doit désigner le même set. Sans TCGdex, les informations seront à compléter à la main.</p>
 <ul className="import-card-preview">{item.cards.slice(0,30).map(card=><li key={card.number}>n° {card.number} · {card.name}</li>)}</ul>{item.cards.length>30&&<p>{item.cards.length-30} autre(s) carte(s) dans cette checklist.</p>}
 {canImport&&<><label className="import-confirm"><input type="checkbox" checked={confirmed} disabled={disabled||!item.complete} onChange={event=>setConfirmed(event.target.checked)}/><span>Je valide cette correspondance et l’ajout des cartes absentes. Le set recevant de nouvelles cartes passera inactif pour vérification ; les cartes et scans existants seront conservés.</span></label><button className="button game-primary" type="button" disabled={disabled||!confirmed||!item.complete||!item.cards.length} onClick={()=>approve({kind:"import",reportId,sourceCode:item.sourceCode,localCode,tcgdexId,confirm:true})}><Download aria-hidden="true"/>Valider l’import de ce set</button></>}
 {!item.complete&&<p>Import bloqué : la checklist n’a pas été lue intégralement.</p>}</details></article>;
}
export function AdminImports({initial,canImport}:{initial:Dashboard;canImport:boolean}){
 const [data,setData]=useState(initial),[query,setQuery]=useState(""),[filter,setFilter]=useState("missing"),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function reload(){try{const response=await fetch("/api/admin/imports",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);}catch(reason){setError(reason instanceof Error?reason.message:"Chargement impossible.");}}
 useEffect(()=>{const timer=setInterval(()=>void reload(),15000);return ()=>clearInterval(timer);},[]);
 async function queue(body:Record<string,unknown>){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error);setNotice(body.kind==="scan"?"Recherche demandée. Le rapport se remplit progressivement.":"Import validé. Son avancement apparaît dans les tâches.");await reload();}catch(reason){setError(reason instanceof Error?reason.message:"Action impossible.");}finally{setBusy(false);}}
 const active=data.jobs.some(job=>["queued","running"].includes(job.status)),report=data.jobs.find(job=>job.id===data.reportId),filtered=data.items.filter(item=>(item.sourceCode+" "+item.name).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="missing"&&item.missing>0||filter==="issues"&&item.issues.length>0));
 const workerOnline=!!data.schedule?.heartbeat&&Date.now()-new Date(data.schedule.heartbeat).getTime()<120000;
 return <><div className="admin-config-summary"><div><span>PROCHAINE RECHERCHE · PARIS</span><strong>{time(data.schedule?.nextRun)}</strong></div><div><span>SERVICE DE CATALOGUE</span><strong>{workerOnline?"Disponible":"En attente du service"}</strong></div><div><span>IMPORTS</span><strong>Validation manuelle obligatoire</strong></div></div>
 <section className="admin-target-panel import-intro"><h2><CalendarClock aria-hidden="true"/>Recherche hebdomadaire</h2><p>Le service compare les checklists françaises de Pokécardex au catalogue du jeu. Les noms et numéros des cartes viennent de Pokécardex ; les informations complémentaires viennent de TCGdex lorsqu’elles sont disponibles.</p><p>Les codes peuvent différer entre les sources. Vérifie chaque correspondance avant de valider. Une lecture partielle ne permet pas de conclure que rien ne manque.</p><div className="metadata-actions">{canImport&&<button className="button game-primary" disabled={busy||active} onClick={()=>queue({kind:"scan"})}><Search aria-hidden="true"/>Rechercher maintenant</button>}<button className="quiet-button" disabled={busy} onClick={()=>void reload()}><RefreshCw aria-hidden="true"/>Actualiser</button><Link className="quiet-button" href="/admin/catalogue">Compléter les fiches</Link></div>{!canImport&&<p>Consultation seule. La permission « Rechercher et valider les imports » est nécessaire pour agir.</p>}{error&&<p role="alert" className="admin-catalogue-error">{error}</p>}{notice&&<p role="status" className="admin-catalogue-notice">{notice}</p>}</section>
 <section className="admin-target-panel import-report"><h2>Le dernier rapport</h2>{report?<><p>{statuses[report.status]} · {time(report.createdAt)} · {report.progress} / {report.total} séries</p><p role="status">{report.summary}</p></>:<p>Aucune recherche réalisée pour le moment.</p>}<div className="admin-catalogue-filters"><label>Rechercher une série<input value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Code ou nom"/></label><label>Afficher<select value={filter} onChange={event=>{setFilter(event.target.value);setPage(0);}}><option value="missing">Cartes absentes</option><option value="issues">Points à vérifier</option><option value="all">Toutes les séries</option></select></label></div><p>{filtered.length} série(s) dans ce filtre.</p>
 {filtered.slice(page*12,(page+1)*12).map(item=><Proposal key={data.reportId+item.sourceCode} item={item} reportId={data.reportId!} canImport={canImport} disabled={busy||active||!workerOnline} approve={queue}/>)}
 <nav className="admin-pagination" aria-label="Pages du rapport"><button className="quiet-button" disabled={page===0} onClick={()=>setPage(value=>value-1)}>Précédente</button><span>Page {page+1} / {Math.max(1,Math.ceil(filtered.length/12))}</span><button className="quiet-button" disabled={(page+1)*12>=filtered.length} onClick={()=>setPage(value=>value+1)}>Suivante</button></nav></section>
 <section className="admin-target-panel import-history"><h2>Les dernières tâches</h2>{data.jobs.map(job=><article key={job.id}><strong>{job.kind==="scan"?"Recherche":"Import"} · {statuses[job.status]}</strong><span>{time(job.createdAt)} · {job.actorName}</span><p>{job.summary||"En attente du service."}</p><p>{job.progress} / {job.total}</p></article>)}{!data.jobs.length&&<p>Aucune tâche enregistrée.</p>}</section></>;
}
