"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Plus,Pencil,Trash2,RefreshCw,Tags } from "lucide-react";
import type { RarityOverview,RarityView } from "@/lib/rarity-types";
export function AdminRarities({initial,canCreate,canEdit,canDelete}:{initial:RarityOverview;canCreate:boolean;canEdit:boolean;canDelete:boolean;canReviewPrices:boolean}){
 const [data,setData]=useState(initial),[name,setName]=useState(""),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false);
 const [edit,setEdit]=useState<RarityView|null>(null),[newName,setNewName]=useState("");
 const operation=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(edit){operation.current?.scrollIntoView({block:"center",behavior:"auto"});operation.current?.focus({preventScroll:true});}},[edit]);
 async function mutate(body:Record<string,unknown>){if(busy)return;setBusy(true);setMessage("");try{
  const r=await fetch("/api/admin/rarities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,token:data.token})}),d=await r.json();
  if(!r.ok){setConflict(r.status===409);throw Error(d.error??"Opération impossible.");}
  setData(d);setName("");setEdit(null);setConflict(false);setMessage(body.action==="delete"?"Rareté supprimée.":"Liste des raretés enregistrée.");
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function reload(){if(edit&&!window.confirm("Abandonner ce brouillon et recharger la liste ?"))return;setBusy(true);try{const r=await fetch("/api/admin/rarities",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error??"Chargement impossible.");setData(d);setEdit(null);setConflict(false);setMessage("Liste rechargée.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><section className="admin-target-panel"><div className="admin-section-heading"><Tags aria-hidden="true"/><div><h2>Ta liste de raretés</h2><p>Les exemplaires déjà obtenus gardent leurs informations d’origine. Supprimer retire la rareté de cette liste, sans remplacement automatique.</p></div></div>
 <div className="rarity-tools"><form onSubmit={e=>{e.preventDefault();void mutate({action:"create",name});}}><label>Nouvelle rareté<input required maxLength={160} value={name} disabled={!canCreate||busy} onChange={e=>setName(e.target.value)}/></label><button className="button game-primary" disabled={!canCreate||busy||!name.trim()||conflict}><Plus size={18}/>Créer la rareté</button></form><label>Rechercher une rareté<input type="search" value={filter} onChange={e=>setFilter(e.target.value)}/></label><button type="button" className="quiet-button" disabled={busy} onClick={reload}><RefreshCw size={18}/>Recharger</button></div>
 <p className="admin-helper">Les références à une rareté supprimée restent à réattribuer dans le catalogue et les réglages concernés. Les couleurs se règlent dans <Link href="/admin/boosters#effets-rarete">Boosters et cadeaux</Link>.</p>
 <div className="rarity-list">{data.rarities.filter(r=>(r.name+" "+r.aliases.join(" ")).toLocaleLowerCase("fr").includes(filter.toLocaleLowerCase("fr"))).map(r=><article className="rarity-entry" key={r.id}><div><h3>{r.name}</h3><p>{r.cards} référence(s) de cartes · {r.copies} exemplaire(s) historique(s) · {r.boosterSets.length} composition(s) · {r.priceCount} tarif(s)</p>{r.aliases.length>0&&<details><summary>Anciens noms et correspondances ({r.aliases.length})</summary><p>{r.aliases.join(" · ")}</p></details>}</div><div className="rarity-entry-actions"><button type="button" className="quiet-button" disabled={!canEdit||busy||conflict} aria-label={"Modifier "+r.name} onClick={()=>{setEdit(r);setNewName(r.name);setMessage("");}}><Pencil size={16}/>Modifier</button><button type="button" className="quiet-button" disabled={!canDelete||busy} aria-label={"Supprimer "+r.name} onClick={()=>void mutate({action:"delete",id:r.id,revision:r.revision})}><Trash2 size={16}/>Supprimer</button></div></article>)}</div>
 {!data.rarities.length&&<p>Aucune rareté. Crée la première entrée.</p>}</section>
 {edit&&<section className="admin-target-panel rarity-operation" aria-labelledby="rarity-operation-title"><h2 ref={operation} tabIndex={-1} id="rarity-operation-title">Modifier « {edit.name} »</h2><form onSubmit={e=>{e.preventDefault();void mutate({action:"rename",id:edit.id,name:newName,pricePolicy:"target"});}}><fieldset disabled={busy}><legend className="sr-only">Modifier le nom de la rareté</legend><label>Nouveau nom<input required maxLength={160} value={newName} onChange={e=>setNewName(e.target.value)}/></label></fieldset><div className="metadata-actions"><button className="button game-primary" disabled={busy||conflict} type="submit">Enregistrer le nom</button><button type="button" className="quiet-button" disabled={busy} onClick={()=>setEdit(null)}>Annuler</button></div></form></section>}
 {data.unregistered.length>0&&<section className="admin-target-panel"><h2>Libellés importés absents de ta liste</h2><p>Ces cartes restent à compléter tant qu’une rareté du jeu n’est pas choisie. Crée une entrée ou réattribue les cartes depuis leurs fiches.</p><ul>{data.unregistered.map(r=><li key={r.name}>{r.name} · {r.cards} référence(s){canCreate&&<button className="quiet-button" disabled={busy} type="button" onClick={()=>setName(r.name)}>Préparer cette rareté</button>}</li>)}</ul></section>}
 <div className="rarity-status" role="status" aria-live="polite">{message}{conflict&&<button type="button" className="quiet-button" disabled={busy} onClick={reload}>Recharger la liste</button>}</div></>;
}
