"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { availableFinishes,finishLabels,missingMetadata,type CardMetadataView,type CardMetadataFields } from "@/lib/card-metadata";
export function CardMetadataEditor({initial,canEdit,rarityOptions}:{initial:CardMetadataView;canEdit:boolean;rarityOptions:string[]}){
 const router=useRouter();
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState<CardMetadataFields>(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[file,setFile]=useState<File|null>(null);
 const missing=missingMetadata(draft,saved.imageAvailable);
 async function save(event:React.FormEvent){
  event.preventDefault();setBusy(true);setError("");setNotice("");
  try{const response=await fetch("/api/admin/cards",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,setCode:saved.setCode,id:saved.id,revision:saved.revision})});const value=await response.json();if(!response.ok)throw new Error(value.error);setSaved(value);setDraft(value);setNotice("Fiche enregistrée. Le set doit être activé séparément une fois toutes ses cartes complètes.");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Enregistrement impossible.");}finally{setBusy(false);}
 }
 async function reload(){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/cards?set="+encodeURIComponent(saved.setCode)+"&card="+encodeURIComponent(saved.id),{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error);setSaved(value);setDraft(value);setNotice("Fiche rechargée.");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Chargement impossible.");}finally{setBusy(false);}}
 async function upload(){if(!file)return;setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/cards/image?set="+encodeURIComponent(saved.setCode)+"&card="+encodeURIComponent(saved.id)+"&revision="+saved.revision,{method:"POST",headers:{"Content-Type":file.type},body:file});const value=await response.json();if(!response.ok)throw new Error(value.error);setSaved(value);setFile(null);setNotice("Image ajoutée. Pense à enregistrer les autres informations de la fiche.");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Ajout impossible.");}finally{setBusy(false);}}
 return <section className="admin-target-panel metadata-editor" aria-busy={busy}>
 <div className="metadata-image">{saved.imageAvailable?<img src={"/media/Cards/"+saved.setCode+"/"+saved.id+".png?v="+saved.revision} alt={saved.name||"Carte à compléter"}/>:<p className="metadata-empty">Image manquante</p>}<p>{saved.imageAvailable?"Image conservée. Elle ne sera pas remplacée.":"Ajoute le scan manquant : PNG, JPEG ou WebP, 8 Mo maximum."}</p>{canEdit&&!saved.imageAvailable&&<><label>Scan de la carte<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={event=>setFile(event.target.files?.[0]??null)}/></label><button className="quiet-button" disabled={busy||!file} type="button" onClick={upload}>Ajouter l’image</button></>}</div>
 <form onSubmit={save}><h2>La fiche de la carte</h2><p className="admin-helper">{saved.source==="manual"?"Corrections manuelles":"Informations importées"} · Révision {saved.revision}</p>
 <fieldset disabled={!canEdit||busy} className="metadata-fields"><legend>Informations obligatoires</legend>{([["name","Nom"],["localId","Numéro"],["illustrator","Illustrateur"]] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} maxLength={160} onChange={event=>setDraft(previous=>({...previous,[key]:event.target.value}))}/></label>)}<label>Rareté<select value={draft.rarity} onChange={event=>setDraft(previous=>({...previous,rarity:event.target.value}))}><option value="">Rareté à définir</option>{draft.rarity&&!rarityOptions.includes(draft.rarity)&&<option value={draft.rarity}>{draft.rarity} · absente de la liste</option>}{rarityOptions.map(name=><option value={name} key={name}>{name}</option>)}</select></label></fieldset>
 <fieldset disabled={!canEdit||busy} className="metadata-finishes"><legend>Finition unique de la carte</legend>{availableFinishes.map(finish=><label key={finish}><input type="radio" name="card-finish" checked={draft.finishes.length===1&&draft.finishes[0]===finish} onChange={event=>setDraft(previous=>({...previous,finishes:[finish]}))}/>{finishLabels[finish]}</label>)}</fieldset>
 <p className={missing.length?"admin-catalogue-error":"admin-catalogue-notice"}>{missing.length?"À compléter : "+missing.join(", "):"Les six informations sont renseignées."}</p><p>Tu peux enregistrer une fiche incomplète. L’activation du set reste bloquée tant que toutes ses cartes ne sont pas complètes, y compris les cartes exclues.</p>
 {error&&<p role="alert" className="admin-catalogue-error">{error}</p>}{notice&&<p role="status" className="admin-catalogue-notice">{notice}</p>}
 <div className="metadata-actions">{canEdit&&<button className="button game-primary" disabled={busy} type="submit">Enregistrer la fiche</button>}<button className="quiet-button" disabled={busy} type="button" onClick={reload}>Recharger la fiche</button></div>{!canEdit&&<p>Consultation seule.</p>}
 </form></section>;
}
