"use client";
import { useEffect,useState } from "react";
import { CardViewer } from "./card-viewer";
import { finishLabels } from "@/lib/card-metadata";
import { activeDefectNames } from "@/lib/card-defects";
import { DefectSurface } from "./defect-surface";
import type { CollectionCard } from "@/lib/booster-types";
import { CollectionFilterBar } from "./collection-filter-bar";
import { CollectionMissing } from "./collection-missing";
import { CollectionSetProgressPanel } from "./collection-set-progress";
import type { CollectionSetProgress } from "@/lib/collection-progress-types";
import { CollectionCardSearch } from "./collection-card-search";
import { emptyCollectionFilters, type CollectionFilters, type CollectionFilterOptions } from "@/lib/collection-filters";
export function PlayerCollection({pseudo}:{pseudo?:string}){
 const [cards,setCards]=useState<CollectionCard[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [groupsTotal,setGroupsTotal]=useState(0);
 const [progress,setProgress]=useState<CollectionSetProgress[]>([]);
 const [missingCode,setMissingCode]=useState("");
 const [revision,setRevision]=useState(0);
 const [filters,setFilters]=useState<CollectionFilters>({...emptyCollectionFilters});
 const [options,setOptions]=useState<CollectionFilterOptions>({sets:[],rarities:[]});
 const filtered=Object.values(filters).some(Boolean);
 function changeFilters(next:CollectionFilters){setCards([]);setProgress([]);setTotal(0);setGroupsTotal(0);setLoading(true);setFilters(next);setPage(0);}
 useEffect(()=>{const c=new AbortController();setLoading(true);setError("");setCards([]);setProgress([]);setTotal(0);setGroupsTotal(0);const query=new URLSearchParams({page:String(page),...filters});fetch((pseudo?"/api/player/collections/"+encodeURIComponent(pseudo):"/api/player/collection")+"?"+query,{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setCards(d.cards);setProgress(d.progress??[]);setTotal(d.total);setGroupsTotal(d.groupsTotal??d.total);setOptions(d.options??{sets:[],rarities:[]});}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setOptions({sets:[],rarities:[]});}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[page,pseudo,filters,revision]);
 return <>{!loading&&!error&&<CollectionSetProgressPanel sets={progress} onSelect={setCode=>{setMissingCode("");changeFilters({...emptyCollectionFilters,setCode});}} onMissing={setMissingCode}/>} {!loading&&!error&&missingCode&&<CollectionMissing key={(pseudo??"own")+":"+missingCode} code={missingCode} pseudo={pseudo} revision={revision} onClose={()=>setMissingCode("")}/>}<CollectionCardSearch value={filters.search} disabled={loading} onSearch={search=>changeFilters({...filters,search})}/><CollectionFilterBar value={filters} options={options} disabled={loading} showFavorites={!pseudo} onChange={changeFilters}/><p className="collection-order-note">Cartes classées par set, puis numéro.</p><p className="collection-count" aria-live="polite">{!loading&&!error?total+" exemplaire(s), "+groupsTotal+" emplacement(s) "+(filtered?"correspondant aux filtres":pseudo?"dans cette collection":"dans ton classeur"):""}</p>{loading&&<p role="status">Chargement des cartes…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!total&&<section className="booster-empty"><h2>{filtered?"Aucune carte ne correspond aux filtres":pseudo?"Ce classeur est encore vide":"Les premières pages attendent tes cartes"}</h2><p>{filtered?"Modifie ou efface les filtres pour retrouver tes résultats.":pseudo?"Aucun exemplaire à consulter pour le moment.":"Ouvre un booster pour commencer ta collection."}</p></section>}<div className="owned-card-grid">{cards.map(c=><article className="owned-card-pocket" key={c.id}><CardViewer card={{id:c.cardId,name:c.name,localId:c.localId,rarity:c.rarity}} setCode={c.setCode} setName={c.setName} owned={c} allowFavorites={!pseudo} onFavoritesChanged={()=>{setPage(0);setRevision(v=>v+1);}} collectionGroup={(c.quantity??1)>1?{anchorId:c.id,pseudo,filters}:undefined}>{c.defects?<div className="owned-pocket-image"><DefectSurface setCode={c.setCode} cardId={c.cardId} neighborId={c.defects.neighborId} settings={c.defects.settings}/></div>:<img src={"/media/Cards/"+c.setCode+"/"+c.cardId+".png"} alt={c.name} loading="lazy"/>}</CardViewer><h2>{c.name}</h2><span className="owned-copy-count" aria-label={(c.quantity??1)+" exemplaire(s) dans ce groupe"}>×{(c.quantity??1).toLocaleString("fr-FR")}</span><p>{c.setCode} · n°{c.localId} · {c.rarity}</p><span className="owned-finish">{finishLabels[c.finish]}</span>{c.defects&&<p>{activeDefectNames(c.defects.settings).join(" · ")}</p>}</article>)}</div>{groupsTotal>24&&<nav className="booster-pagination" aria-label="Pages de la collection"><button type="button" className="quiet-button" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Précédente</button><span>Page {page+1}</span><button type="button" className="quiet-button" disabled={(page+1)*24>=groupsTotal||loading} onClick={()=>setPage(p=>p+1)}>Suivante</button></nav>}</>;
}
