"use client";
import { useState } from "react";
import { Sparkles,Save } from "lucide-react";
import { basicRarity,revealStyle,type RevealConfiguration,type RevealStyle } from "@/lib/booster-reveal";
export function AdminBoosterEffects({initial,rarities,canEdit}:{initial:RevealConfiguration;rarities:string[];canEdit:boolean}){
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.styles),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false);
 const names=[...new Set([...rarities,...Object.keys(draft)])],dirty=JSON.stringify(draft)!==JSON.stringify(saved.styles);
 function change(name:string,patch:Partial<RevealStyle>){setDraft(v=>({...v,[name]:{...revealStyle(name,v),...patch}}));setMessage("");}
 async function save(){if(!canEdit||busy)return;setBusy(true);setMessage("");try{
  const r=await fetch("/api/admin/booster-effects",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({styles:draft,revision:saved.revision})}),d=await r.json();
  if(!r.ok){setConflict(r.status===409);throw Error(d.error??"Enregistrement impossible.");}
  setSaved(d);setDraft(d.styles);setConflict(false);setMessage("Effets de révélation enregistrés.");
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function reload(){if(dirty&&!window.confirm("Abandonner le brouillon et recharger les effets ?"))return;setBusy(true);try{
  const r=await fetch("/api/admin/booster-effects",{cache:"no-store"});if(!r.ok)throw Error("Impossible de recharger les effets.");const d=await r.json();setSaved(d);setDraft(d.styles);setConflict(false);setMessage("Réglages rechargés.");
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section id="effets-rarete" className="admin-target-panel booster-effects-editor"><div className="admin-section-heading"><Sparkles aria-hidden="true"/><div><h2>Révélation des cartes rares</h2><p>Couleurs communes à tous les sets. Le contour et le halo apparaissent après le retournement.</p></div></div><p>Commune et Peu commune restent sans effet spécial. Les raretés inconnues peuvent être réglées ici. La réduction des animations garde le contour fixe.</p>
 <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!canEdit||busy}><legend className="sr-only">Couleurs par rareté</legend><div className="booster-effects-grid">{names.map(name=>{const style=revealStyle(name,draft),basic=basicRarity(name);return <div className="booster-effect-row" key={name}><strong>{name}</strong><label className="admin-check"><input type="checkbox" aria-label={"Effet de révélation · "+name} checked={style.enabled} disabled={basic} onChange={e=>change(name,{enabled:e.target.checked})}/>{basic?"Sans effet spécial":"Effet de révélation"}</label>{!basic&&<label className="reveal-color-field">Couleur<input type="color" aria-label={"Couleur de révélation · "+name} value={style.color} onChange={e=>change(name,{color:e.target.value})}/><span>{style.color.toUpperCase()}</span></label>}<div className="rarity-style-preview" data-enabled={style.enabled} style={{borderColor:style.enabled?style.color:undefined}}><Sparkles aria-hidden="true" style={{color:style.enabled?style.color:undefined}}/><span>{style.enabled?"Contour coloré et halo":"Révélation sobre"}</span></div></div>;})}</div></fieldset>
 <div className="metadata-actions"><button className="button game-primary" disabled={!canEdit||busy||!dirty||conflict} type="submit"><Save size={18}/>{busy?"Enregistrement…":"Enregistrer les effets"}</button><button type="button" className="quiet-button" disabled={busy||!dirty} onClick={()=>{setDraft(saved.styles);setMessage("");}}>Annuler le brouillon</button>{conflict&&<button type="button" className="quiet-button" disabled={busy} onClick={reload}>Recharger les effets</button>}</div><p role="status">{message||(!canEdit?"Consultation des effets":dirty?"Modifications non enregistrées":"Réglages à jour")}</p></form></section>;
}
