"use client";
import {useEffect,useState} from "react";
import {blankEvent,eventPublicationIssues,type EventContent,type EventRow,type EventReward} from "@/lib/event-types";
type SetRef={code:string;name:string};type CardRef={id:string;name:string;localId:string};
async function api(url:string,options?:RequestInit){const r=await fetch(url,{cache:"no-store",...options}),d=await r.json();if(!r.ok)throw Error(d.error??"Opération impossible.");return d;}
function Reference({sets,code,cardId,needCard,optional=false,onChange}:{sets:SetRef[];code:string;cardId:string;needCard:boolean;optional?:boolean;onChange:(code:string,cardId:string)=>void}){
 const[cards,setCards]=useState<CardRef[]>([]),[error,setError]=useState("");
 useEffect(()=>{setCards([]);setError("");if(!code||!needCard)return;const c=new AbortController();api("/api/admin/events?cards="+encodeURIComponent(code),{signal:c.signal}).then(d=>{if(!c.signal.aborted)setCards(d.cards);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[code,needCard]);
 return <><label>Set<select value={code} onChange={e=>onChange(e.target.value,"")}><option value="">{optional?"Tous les sets":"Choisir un set"}</option>{sets.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label>{needCard&&<label>Carte<select value={cardId} disabled={!code} onChange={e=>onChange(code,e.target.value)}><option value="">Choisir une carte</option>{cards.map(c=><option value={c.id} key={c.id}>{c.localId} · {c.name}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}</>;
}
function Rewards({value,onChange,sets,label}:{value:EventReward[];onChange:(v:EventReward[])=>void;sets:SetRef[];label:string}){
 const patch=(id:string,p:Partial<EventReward>)=>onChange(value.map(r=>r.id===id?{...r,...p}:r));
 return <fieldset className="news-block"><legend>{label}</legend>{value.map((r,i)=><fieldset className="news-block" key={r.id}><legend>Récompense {i+1}</legend><label>Type<select value={r.kind} onChange={e=>patch(r.id,{kind:e.target.value as EventReward["kind"],setCode:"",cardId:"",quantity:1})}><option value="booster">Boosters</option><option value="card">Carte précise</option><option value="coins">Pièces</option><option value="gems">Gemmes</option></select></label><label>Quantité<input type="number" min={1} max={r.kind==="card"||r.kind==="booster"?100:1000000} step={1} value={r.quantity} onChange={e=>patch(r.id,{quantity:Number(e.target.value)})}/></label>{(r.kind==="card"||r.kind==="booster")&&<Reference sets={sets} code={r.setCode} cardId={r.cardId} needCard={r.kind==="card"} onChange={(setCode,cardId)=>patch(r.id,{setCode,cardId})}/>}<button className="quiet-button" type="button" onClick={()=>onChange(value.filter(v=>v.id!==r.id))}>Retirer cette récompense</button></fieldset>)}<button className="quiet-button" type="button" disabled={value.length>=20} onClick={()=>onChange([...value,{id:crypto.randomUUID(),kind:"coins",quantity:1,setCode:"",cardId:""}])}>Ajouter une récompense</button></fieldset>;
}
export function AdminEvents({permissions,superAdmin}:{permissions:string[];superAdmin:boolean}){
 const can=(p:string)=>superAdmin||permissions.includes(p);
 const[rows,setRows]=useState<EventRow[]>([]),[sets,setSets]=useState<SetRef[]>([]),[selected,setSelected]=useState<EventRow|null>(null),[draft,setDraft]=useState<EventContent>(blankEvent),[archived,setArchived]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const dirty=!!selected&&JSON.stringify(draft)!==JSON.stringify(selected.draft),editable=!!selected&&!selected.archivedAt&&can("events.edit");
 const issues=eventPublicationIssues(draft);
 useEffect(()=>{const c=new AbortController();setLoading(true);api("/api/admin/events?archived="+(archived?"1":"0"),{signal:c.signal}).then(d=>{if(!c.signal.aborted)setRows(d.events);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[archived]);
 useEffect(()=>{const c=new AbortController();api("/api/admin/events?sets=1",{signal:c.signal}).then(d=>{if(!c.signal.aborted)setSets(d.sets);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 const patch=(p:Partial<EventContent>)=>setDraft(d=>({...d,...p}));
 function choose(row:EventRow|null){if(dirty&&!confirm("Abandonner les changements non enregistrés ?"))return;setSelected(row);setDraft(row?.draft??blankEvent);setError("");setNotice("");}
 async function action(kind:string){
  if(busy)return;if(["archive","unpublish"].includes(kind)&&!confirm(kind==="archive"?"Archiver cet événement et le retirer du site ?":"Retirer cette annonce du site ?"))return;
  setBusy(true);setError("");setNotice("");
  try{const row=await api("/api/admin/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id:selected?.id,revision:selected?.revision,content:kind==="create"?blankEvent:draft})});setSelected(row);setDraft(row.draft);setRows((await api("/api/admin/events?archived="+(archived?"1":"0"))).events);setNotice(kind==="save"?"Brouillon enregistré. L’annonce publiée est conservée.":kind==="restore"?"Événement restauré comme brouillon.":"Action enregistrée.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <section aria-label="Gestion des événements"><div className="news-admin-toolbar"><button className="quiet-button" disabled={busy||dirty} onClick={()=>{choose(null);setArchived(v=>!v);}}>{archived?"Voir les événements":"Voir les archives"}</button>{can("events.create")&&<button className="button game-primary" disabled={busy||dirty} onClick={()=>void action("create")}>Nouvel événement</button>}</div><p className="news-status">Les annonces datées sont disponibles. Les objectifs et récompenses des défis peuvent être préparés ; leur publication attend le moteur de progression et le bouton de récupération.</p>{error&&<p className="admin-catalogue-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Chargement…</p>}
 {!selected?<div className="news-list">{!loading&&!rows.length&&<p className="news-empty">{archived?"Aucun événement archivé.":"Aucun événement. Crée un premier brouillon."}</p>}{rows.map(r=><article key={r.id}><span className="quest-label">{r.archivedAt?"Archivé":r.published?"Publié · brouillon modifiable":"Brouillon"} · {r.draft.kind==="playable"?"Défi jouable":"Annonce"}</span><h2>{r.draft.title||"Sans titre"}</h2><p>{r.draft.summary}</p><button className="quiet-button" onClick={()=>choose(r)}>Ouvrir</button></article>)}</div>:<>
 <button className="quiet-button" disabled={busy} onClick={()=>choose(null)}>Retour à la liste</button><section className="admin-settings-panel news-editor"><h2>Préparer l’événement</h2><p>Révision {selected.revision}. Les modifications restent en brouillon jusqu’à publication.</p><fieldset disabled={busy||!editable}><legend>Présentation et calendrier</legend><label>Type<select value={draft.kind} onChange={e=>{const kind=e.target.value as EventContent["kind"];if(kind==="announcement"&&(draft.objectives.length||draft.rewards.length)&&!confirm("Retirer les objectifs et récompenses du brouillon pour en faire une annonce ?"))return;patch({kind,...(kind==="announcement"?{objectives:[],rewards:[]}:{})});}}><option value="announcement">Annonce datée</option><option value="playable">Défi jouable (en préparation)</option></select></label><label>Titre<input maxLength={160} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label><label>Résumé<textarea maxLength={400} value={draft.summary} onChange={e=>patch({summary:e.target.value})}/></label><label>Description<textarea maxLength={8000} value={draft.description} onChange={e=>patch({description:e.target.value})}/></label><label>Début (Europe/Paris)<input type="datetime-local" value={draft.starts} onChange={e=>patch({starts:e.target.value})}/></label><label>Fin (Europe/Paris)<input type="datetime-local" value={draft.ends} onChange={e=>patch({ends:e.target.value})}/></label>
 {draft.kind==="playable"&&<><h3>Objectifs · acquisitions pendant l’événement seulement</h3>{draft.objectives.map((o,i)=><fieldset className="news-block" key={o.id}><legend>Objectif {i+1}</legend><label>Action<select value={o.kind} onChange={e=>patch({objectives:draft.objectives.map(x=>x.id===o.id?{...x,kind:e.target.value as "boosters"|"card",setCode:"",cardId:""}:x)})}><option value="boosters">Ouvrir des boosters</option><option value="card">Obtenir une carte précise</option></select></label><label>Quantité<input type="number" min={1} max={100000} step={1} value={o.quantity} onChange={e=>patch({objectives:draft.objectives.map(x=>x.id===o.id?{...x,quantity:Number(e.target.value)}:x)})}/></label><Reference sets={sets} code={o.setCode} cardId={o.cardId} needCard={o.kind==="card"} optional={o.kind==="boosters"} onChange={(setCode,cardId)=>patch({objectives:draft.objectives.map(x=>x.id===o.id?{...x,setCode,cardId}:x)})}/><Rewards sets={sets} value={o.rewards} label="Récompenses de cet objectif" onChange={rewards=>patch({objectives:draft.objectives.map(x=>x.id===o.id?{...x,rewards}:x)})}/><button className="quiet-button" type="button" onClick={()=>patch({objectives:draft.objectives.filter(x=>x.id!==o.id)})}>Retirer cet objectif</button></fieldset>)}<button className="quiet-button" type="button" disabled={draft.objectives.length>=20} onClick={()=>patch({objectives:[...draft.objectives,{id:crypto.randomUUID(),kind:"boosters",quantity:1,setCode:"",cardId:"",rewards:[]}]})}>Ajouter un objectif</button><Rewards sets={sets} value={draft.rewards} label="Récompenses finales · tous les objectifs terminés" onChange={rewards=>patch({rewards})}/></>}
 </fieldset><div className="news-actions"><button className="button game-primary" disabled={busy||!editable||!dirty} onClick={()=>void action("save")}>Enregistrer le brouillon</button></div></section>
 <section className="admin-settings-panel"><h2>Publication</h2>{!selected.archivedAt&&<div className="news-readiness">{issues.length?<><h3>À préparer avant publication</h3><ul>{issues.map(issue=><li key={issue}>{issue}</li>)}</ul></>:<p>Annonce prête à publier.</p>}{dirty&&<p>Enregistre d’abord le brouillon.</p>}</div>}<div className="news-actions">{can("events.publish")&&!selected.archivedAt&&<><button className="button game-primary" disabled={busy||dirty||issues.length>0} onClick={()=>void action("publish")}>Publier l’annonce</button><button className="quiet-button" disabled={busy||dirty||!selected.published} onClick={()=>void action("unpublish")}>Dépublier</button></>}{can("events.delete")&&<button className="quiet-button" disabled={busy||dirty} onClick={()=>void action(selected.archivedAt?"restore":"archive")}>{selected.archivedAt?"Restaurer comme brouillon":"Archiver"}</button>}{selected.published&&!selected.archivedAt&&<a className="quiet-button" href={"/evenements/"+selected.id}>Voir l’annonce publique</a>}</div></section>
 </>}</section>;
}
