"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Plus,Pencil,Trash2,RefreshCw,Tags } from "lucide-react";
import type { RarityOverview,RarityView } from "@/lib/rarity-types";
export function AdminRarities({initial,canCreate,canEdit,canDelete,canReviewPrices}:{initial:RarityOverview;canCreate:boolean;canEdit:boolean;canDelete:boolean;canReviewPrices:boolean}){
 const [data,setData]=useState(initial),[name,setName]=useState(""),[filter,setFilter]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false);
 const [edit,setEdit]=useState<{kind:"rename"|"delete";row:RarityView}|null>(null),[newName,setNewName]=useState(""),[replacement,setReplacement]=useState(""),[pricePolicy,setPricePolicy]=useState("target"),[effectPolicy,setEffectPolicy]=useState("target");
 const operation=useRef<HTMLHeadingElement>(null);useEffect(()=>{if(edit){operation.current?.scrollIntoView({block:"center",behavior:"auto"});operation.current?.focus({preventScroll:true});}},[edit]);
 const target=data.rarities.find(r=>r.id===replacement),used=edit&&!!(edit.row.cards||edit.row.copies||edit.row.boosterSets.length||edit.row.priceCount);
 async function mutate(body:Record<string,unknown>){setBusy(true);setMessage("");try{
  const r=await fetch("/api/admin/rarities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,token:data.token})}),d=await r.json();
  if(!r.ok){setConflict(r.status===409);throw Error(d.error??"Opération impossible.");}
  setData(d);setName("");setEdit(null);setConflict(false);setMessage("Liste des raretés enregistrée.");
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function reload(){if(edit&&!window.confirm("Abandonner ce brouillon et recharger la liste ?"))return;setBusy(true);try{const r=await fetch("/api/admin/rarities",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error??"Chargement impossible.");setData(d);setEdit(null);setConflict(false);setMessage("Liste rechargée.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function open(kind:"rename"|"delete",row:RarityView){setEdit({kind,row});setNewName(row.name);setReplacement("");setPricePolicy("target");setEffectPolicy("target");setMessage("");}
 return <><section className="admin-target-panel"><div className="admin-section-heading"><Tags aria-hidden="true"/><div><h2>Ta liste de raretés</h2><p>Les anciens noms restent des correspondances d’import. Les cartes déjà obtenues et les anciens tirages gardent leurs informations d’origine.</p></div></div>
 <div className="rarity-tools"><form onSubmit={e=>{e.preventDefault();void mutate({action:"create",name});}}><label>Nouvelle rareté<input required maxLength={160} value={name} disabled={!canCreate||busy} onChange={e=>setName(e.target.value)}/></label><button className="button game-primary" disabled={!canCreate||busy||!name.trim()||conflict}><Plus size={18}/>Créer la rareté</button></form><label>Rechercher une rareté<input type="search" value={filter} onChange={e=>setFilter(e.target.value)}/></label><button type="button" className="quiet-button" disabled={busy} onClick={reload}><RefreshCw size={18}/>Recharger</button></div>
 <p className="admin-helper">Modifier une rareté utilisée peut aussi nécessiter les droits de modification du catalogue, des boosters et des tarifs. Les couleurs se règlent dans <Link href="/admin/boosters#effets-rarete">Boosters et cadeaux</Link>.</p>
 <div className="rarity-list">{data.rarities.filter(r=>(r.name+" "+r.aliases.join(" ")).toLocaleLowerCase("fr").includes(filter.toLocaleLowerCase("fr"))).map(r=><article className="rarity-entry" key={r.id}><div><h3>{r.name}</h3><p>{r.cards} référence(s) de cartes · {r.copies} exemplaire(s) historique(s) · {r.boosterSets.length} composition(s) · {r.priceCount} tarif(s)</p>{r.aliases.length>0&&<details><summary>Anciens noms et correspondances ({r.aliases.length})</summary><p>{r.aliases.join(" · ")}</p></details>}</div><div className="rarity-entry-actions"><button type="button" className="quiet-button" disabled={!canEdit||busy||conflict} aria-label={"Modifier "+r.name} onClick={()=>open("rename",r)}><Pencil size={16}/>Modifier</button><button type="button" className="quiet-button" disabled={!canDelete||busy||conflict} aria-label={"Supprimer "+r.name} onClick={()=>open("delete",r)}><Trash2 size={16}/>Supprimer</button></div></article>)}</div>
 {!data.rarities.length&&<p>Aucune rareté. Crée la première entrée.</p>}</section>
 {edit&&<section className="admin-target-panel rarity-operation" aria-labelledby="rarity-operation-title"><h2 ref={operation} tabIndex={-1} id="rarity-operation-title">{edit.kind==="rename"?"Modifier":"Supprimer"} « {edit.row.name} »</h2><p>{edit.row.cards} référence(s) de cartes, {edit.row.copies} exemplaire(s) historique(s), {edit.row.boosterSets.length} composition(s) et {edit.row.priceCount} tarif(s) concerné(s).</p>
 <form onSubmit={e=>{e.preventDefault();void mutate({action:edit.kind,id:edit.row.id,name:newName,replacementId:replacement||undefined,pricePolicy,effectPolicy});}}>
 <fieldset disabled={busy}><legend className="sr-only">Opération sur la rareté</legend>
 {edit.kind==="rename"?<label>Nouveau nom<input required maxLength={160} value={newName} onChange={e=>setNewName(e.target.value)}/></label>:<><label>Rareté de remplacement<select required={!!used} value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">{used?"Choisis une rareté":"Aucun remplacement (entrée inutilisée)"}</option>{data.rarities.filter(r=>r.id!==edit.row.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><p>La rareté choisie recevra les correspondances d’import et les références actuelles. Les anciennes ouvertures et les exemplaires historiques restent conservés.</p></>}
 {target&&<div className="rarity-replacement-preview"><h3>« {edit.row.name} » → « {target.name} »</h3>{edit.row.boosterSets.length>0&&<p>Compositions mises à jour : {edit.row.boosterSets.join(", ")}. Deux choix devenus identiques seront regroupés avec la somme de leurs poids.</p>}
 {edit.row.priceCount>0&&<><label>En cas de tarifs différents<select value={pricePolicy} onChange={e=>setPricePolicy(e.target.value)}><option value="target">Conserver les tarifs du remplacement en priorité</option><option value="source">Conserver les tarifs de la rareté supprimée en priorité</option></select></label><p>Une monnaie non renseignée reprend l’autre valeur disponible. Zéro reste un tarif explicite.</p>{canReviewPrices?<div className="rarity-price-comparison">{[edit.row,target].map(r=><article key={r.id}><strong>{r.name}</strong>{r.priceRules.length?r.priceRules.map(p=><p key={p.finish}>{p.finish} : {p.coins??"À définir"} pièces · {p.gems??"À définir"} gemmes</p>):<p>Aucun tarif général enregistré</p>}</article>)}</div>:<p>Les permissions de consultation et modification des tarifs sont nécessaires pour transférer ces règles.</p>}</>}
 <label>Couleur et effet configurés<select value={effectPolicy} onChange={e=>setEffectPolicy(e.target.value)}><option value="target">Conserver ceux du remplacement en priorité</option><option value="source">Conserver ceux de la rareté supprimée en priorité</option></select></label><p>En l’absence de réglage enregistré, l’autre réglage est conservé. Commune et Peu commune restent sans effet spécial.</p></div>}
 </fieldset><div className="metadata-actions"><button className="button game-primary" disabled={busy||conflict||(edit.kind==="delete"&&!!used&&!replacement)} type="submit">{edit.kind==="rename"?"Enregistrer le nom":"Confirmer la suppression"}</button><button type="button" className="quiet-button" disabled={busy} onClick={()=>setEdit(null)}>Annuler</button></div></form></section>}
 {data.unregistered.length>0&&<section className="admin-target-panel"><h2>Libellés importés absents de ta liste</h2><p>Ces cartes restent à compléter tant qu’une rareté du jeu n’est pas choisie. Crée une entrée ou réattribue les cartes depuis leurs fiches.</p><ul>{data.unregistered.map(r=><li key={r.name}>{r.name} · {r.cards} référence(s){canCreate&&<button className="quiet-button" disabled={busy} type="button" onClick={()=>setName(r.name)}>Préparer cette rareté</button>}</li>)}</ul></section>}
 <div className="rarity-status" role="status" aria-live="polite">{message}{conflict&&<button type="button" className="quiet-button" disabled={busy} onClick={reload}>Recharger la liste</button>}</div></>;
}
