"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { Gift,Plus,Trash2,Save,RefreshCw } from "lucide-react";
import { type BoosterComposition,type BoosterSlot } from "@/lib/booster-types";
type Setup={setCode:string;name:string;active:boolean;complete:boolean;incomplete:number;rarities:string[];composition:BoosterComposition|null;revision:number};
type Player={id:string;pseudo:string|null;username:string|null};
type History={id:string;setCode:string;quantity:number;reason:string;pseudo:string|null;username:string|null;createdAt:string};
const empty:BoosterComposition={slots:[],defectPpm:0};
export function AdminBoosters({sets,canEdit,canGrant}:{sets:{code:string;name:string;active:boolean}[];canEdit:boolean;canGrant:boolean}){
 const [code,setCode]=useState(sets[0]?.code??""),[setup,setSetup]=useState<Setup|null>(null),[draft,setDraft]=useState<BoosterComposition>(empty);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reload,setReload]=useState(0);
 const [query,setQuery]=useState(""),[players,setPlayers]=useState<Player[]>([]),[playerId,setPlayerId]=useState(""),[quantity,setQuantity]=useState(1),[reason,setReason]=useState("");
 const [history,setHistory]=useState<History[]>([]),requestId=useRef<string|null>(null);
 const dirty=JSON.stringify(draft)!==JSON.stringify(setup?.composition??empty);
 async function response(url:string,options?:RequestInit){const r=await fetch(url,{cache:"no-store",...options}),data=await r.json();if(!r.ok)throw Error(data.error??"Opération impossible.");return data;}
 useEffect(()=>{
  if(!code)return;const abort=new AbortController();setLoading(true);setSetup(null);setError("");setNotice("");
  response("/api/admin/boosters?set="+encodeURIComponent(code),{signal:abort.signal}).then(data=>{if(!abort.signal.aborted){setSetup(data);setDraft(data.composition??{slots:[],defectPpm:0});}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});
  return()=>abort.abort();
 },[code,reload]);
 async function loadHistory(){try{setHistory((await response("/api/admin/boosters?history=1")).history);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void loadHistory();},[]);
 function editSlot(index:number,slot:BoosterSlot){setDraft(d=>({...d,slots:d.slots.map((s,i)=>i===index?slot:s)}));setNotice("");}
 async function save(){setBusy(true);setError("");setNotice("");try{const data=await response("/api/admin/boosters",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({setCode:code,revision:setup?.revision??0,composition:draft})});setSetup(data);setDraft(data.composition);setNotice("Composition enregistrée pour tous les boosters de ce set.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function search(){setBusy(true);setError("");try{setPlayers((await response("/api/admin/boosters?players="+encodeURIComponent(query))).players);setPlayerId("");requestId.current=null;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function grant(){
  if(!window.confirm("Offrir "+quantity+" booster(s) "+code+" au joueur sélectionné ?"))return;
  setBusy(true);setError("");setNotice("");requestId.current??=crypto.randomUUID();
  try{await response("/api/admin/boosters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:requestId.current,setCode:code,userId:playerId,quantity,reason})});setNotice(quantity+" booster(s) attribué(s).");requestId.current=null;setReason("");await loadHistory();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <>
 <section className="admin-settings-panel booster-admin-select"><label>Set à configurer<select value={code} disabled={busy} onChange={e=>{if(dirty&&!window.confirm("Abandonner la composition non enregistrée ?"))return;setCode(e.target.value);requestId.current=null;}}>{sets.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><p>Chaque visuel de booster utilise cette même composition. La composition actuelle est utilisée au moment de l’ouverture ; elle est ensuite conservée dans l’historique du booster.</p></section>
 {loading&&<p role="status">Chargement du set…</p>}
 {setup&&<><section className="admin-target-panel"><h2>{setup.name}</h2><Link className="quiet-button" href={"/admin/boosters/apercu?set="+encodeURIComponent(code)}>Voir l’animation sans attribuer de cartes</Link><p>{setup.active?"Set actif":"Set inactif"} · {setup.complete?"Toutes les fiches sont complètes":setup.incomplete+" fiche(s) à compléter"}</p><p>Les cadeaux et les ouvertures nécessitent un set actif, complet et une carte éligible pour chaque rareté choisie.</p></section>
 <form className="admin-settings-panel booster-composition" onSubmit={e=>{e.preventDefault();void save();}}>
 <h2>Composition du booster</h2><p>Ajoute des groupes de cartes. Dans chaque groupe, les poids définissent la probabilité d’une rareté. Une seule rareté garantit cette rareté. Les cartes sont ensuite tirées équitablement dans la rareté retenue ; les doublons sont possibles.</p>
 {!draft.slots.length&&<p>Aucune composition enregistrée. Aucun tirage ni taux n’est inventé automatiquement.</p>}
 <fieldset disabled={!canEdit||busy||loading}><legend>Groupes de cartes</legend>{draft.slots.map((slot,index)=><div className="booster-slot-editor" key={index}><header><h3>Groupe {index+1}</h3><button type="button" className="quiet-button" aria-label={"Supprimer le groupe "+(index+1)} onClick={()=>setDraft(d=>({...d,slots:d.slots.filter((_,i)=>i!==index)}))}><Trash2 size={18}/></button></header>
 <label>Nombre de cartes<input type="number" min={1} max={20} value={slot.count} onChange={e=>editSlot(index,{...slot,count:Number(e.target.value)})}/></label>
 {slot.choices.map((choice,c)=><div className="booster-choice-editor" key={c}><label>Rareté<select value={choice.rarity} onChange={e=>editSlot(index,{...slot,choices:slot.choices.map((v,i)=>i===c?{...v,rarity:e.target.value}:v)})}>{!setup.rarities.includes(choice.rarity)&&<option value={choice.rarity}>{choice.rarity} · indisponible</option>}{setup.rarities.map(r=><option key={r}>{r}</option>)}</select></label><label>Poids<input type="number" min={1} max={1000000} value={choice.weight} onChange={e=>editSlot(index,{...slot,choices:slot.choices.map((v,i)=>i===c?{...v,weight:Number(e.target.value)}:v)})}/></label><span>{(100*choice.weight/slot.choices.reduce((n,v)=>n+v.weight,0)).toLocaleString("fr-FR",{maximumFractionDigits:2})} %</span><button className="quiet-button" type="button" aria-label={"Retirer la rareté "+choice.rarity+" du groupe "+(index+1)} onClick={()=>editSlot(index,{...slot,choices:slot.choices.filter((_,i)=>i!==c)})}><Trash2 size={18}/></button></div>)}
 <button type="button" className="quiet-button" disabled={!setup.rarities.some(r=>!slot.choices.some(c=>c.rarity===r))} onClick={()=>editSlot(index,{...slot,choices:[...slot.choices,{rarity:setup.rarities.find(r=>!slot.choices.some(c=>c.rarity===r))!,weight:1}]})}><Plus size={18}/>Ajouter une rareté</button></div>)}
 <button type="button" className="quiet-button" disabled={draft.slots.length>=20||!setup.rarities.length} onClick={()=>setDraft(d=>({...d,slots:[...d.slots,{count:1,choices:[{rarity:setup.rarities[0],weight:1}]}]}))}><Plus size={18}/>Ajouter un groupe</button>
 <label className="booster-defects-label">Chance d’un défaut, par million de cartes<input type="number" min={0} max={1000} value={draft.defectPpm} onChange={e=>setDraft(d=>({...d,defectPpm:Number(e.target.value)}))}/></label><p>0 désactive les défauts. 1 signifie 1 chance sur 1 000 000 ; maximum 1 000 (0,1 %). Un second défaut utilise à nouveau cette probabilité : le cumul est encore plus rare. Leur valeur de revente reste inchangée.</p></fieldset>
 <div className="admin-save-bar"><strong>{draft.slots.reduce((n,s)=>n+s.count,0)} carte(s) · {dirty?"Brouillon non enregistré":"Composition à jour"}</strong><div className="admin-save-actions"><button type="button" className="quiet-button" disabled={busy} onClick={()=>{if(!dirty||window.confirm("Recharger et abandonner le brouillon ?"))setReload(r=>r+1);}}><RefreshCw size={18}/>Recharger</button><button className="button game-primary" disabled={!canEdit||busy||!dirty||!draft.slots.length}><Save size={18}/>Enregistrer</button></div></div></form>
 {canGrant&&<section className="admin-settings-panel booster-grant"><h2><Gift aria-hidden="true"/>Offrir des boosters</h2><p>Les cadeaux vont directement dans le compte du joueur.</p><label>Rechercher un pseudo<input value={query} minLength={2} maxLength={64} onChange={e=>setQuery(e.target.value)}/></label><button type="button" className="quiet-button" disabled={busy||query.trim().length<2} onClick={search}>Rechercher</button><label>Joueur<select value={playerId} disabled={busy} onChange={e=>{setPlayerId(e.target.value);requestId.current=null;}}><option value="">Sélectionner un joueur</option>{players.map(p=><option key={p.id} value={p.id}>{p.pseudo??p.username}</option>)}</select></label>{players.length===0&&query.length>=2&&<p>La recherche concerne les joueurs dont l’adresse e-mail est vérifiée.</p>}
 <label>Quantité<input type="number" min={1} max={100} value={quantity} onChange={e=>{setQuantity(Number(e.target.value));requestId.current=null;}}/></label><label>Motif<input value={reason} maxLength={200} onChange={e=>{setReason(e.target.value);requestId.current=null;}}/></label><button type="button" className="button game-primary" disabled={busy||dirty||!playerId||!setup.active||!setup.complete||!setup.composition||quantity<1||quantity>100||reason.trim().length<3} onClick={grant}>Offrir les boosters</button><p>Enregistre d’abord les éventuelles modifications de composition.</p></section>}</>}
 {error&&<p className="admin-catalogue-error" role="alert">{error}</p>}{notice&&<p className="admin-catalogue-notice" role="status">{notice}</p>}
 <section className="admin-settings-panel"><h2>Dernières attributions</h2>{!history.length?<p>Aucun cadeau enregistré.</p>:<ul className="booster-grant-history">{history.map(h=><li key={h.id}><strong>{h.pseudo??h.username} · {h.quantity} × {h.setCode}</strong><span>{h.reason} · {new Date(h.createdAt).toLocaleString("fr-FR")}</span></li>)}</ul>}</section>
 </>;
}
