"use client";
import { useEffect,useState } from "react";
import { CardViewer } from "./card-viewer";
import { finishLabels } from "@/lib/card-metadata";
import { activeDefectNames } from "@/lib/card-defects";
import { DefectSurface } from "./defect-surface";
import type { OwnedCard } from "@/lib/booster-types";
export function PlayerCollection(){
 const [cards,setCards]=useState<OwnedCard[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const c=new AbortController();setLoading(true);setError("");fetch("/api/player/collection?page="+page,{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setCards(d.cards);setTotal(d.total);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[page]);
 return <><p className="collection-count">{total} exemplaire(s) dans ton classeur</p>{loading&&<p role="status">Chargement des cartes…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!total&&<section className="booster-empty"><h2>Les premières pages attendent tes cartes</h2><p>Ouvre un booster pour commencer ta collection.</p></section>}<div className="owned-card-grid">{cards.map(c=><article className="owned-card-pocket" key={c.id}><CardViewer card={{id:c.cardId,name:c.name,localId:c.localId,rarity:c.rarity}} setCode={c.setCode} setName={c.setName} owned={c}>{c.defects?<div className="owned-pocket-image"><DefectSurface setCode={c.setCode} cardId={c.cardId} neighborId={c.defects.neighborId} settings={c.defects.settings}/></div>:<img src={"/media/Cards/"+c.setCode+"/"+c.cardId+".png"} alt={c.name} loading="lazy"/>}</CardViewer><h2>{c.name}</h2><p>{c.setCode} · n°{c.localId} · {c.rarity}</p><span className="owned-finish">{finishLabels[c.finish]}</span>{c.defects&&<p>{activeDefectNames(c.defects.settings).join(" · ")}</p>}</article>)}</div>{total>24&&<nav className="booster-pagination" aria-label="Pages de la collection"><button type="button" className="quiet-button" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Précédente</button><span>Page {page+1}</span><button type="button" className="quiet-button" disabled={(page+1)*24>=total||loading} onClick={()=>setPage(p=>p+1)}>Suivante</button></nav>}</>;
}
